#! /bin/sh


. "${HOME}/.cache/wal/colors.sh"

picom &
redshift -l 22.10317:78.17159 &
sxhkd &
$HOME/.config/polybar/launch.sh &

wal -i $HOME/Pictures
light -S 5

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         3
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Zathura desktop='^5' state=fullscreen follow=on
bspc rule -a Icecat desktop='^1'
bspc rule -a mpv desktop='^6' state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"
